package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/Infamous003/graphql-service/graph/model"
)

// Follow is the resolver for the follow field.
func (r *mutationResolver) Follow(ctx context.Context, followerID string, followeeID string) (*model.FollowResponse, error) {
	// Convert IDs from string to int for the Follow Service
	followerIDInt, err := strconv.Atoi(followerID)
	if err != nil {
		msg := "invalid follower ID"
		return &model.FollowResponse{Message: &msg}, nil
	}

	followeeIDInt, err := strconv.Atoi(followeeID)
	if err != nil {
		msg := "invalid followee ID"
		return &model.FollowResponse{Message: &msg}, nil
	}

	// Payload must match Follow Service expected JSON
	payload := map[string]int{
		"follower_id": followerIDInt,
		"followee_id": followeeIDInt,
	}

	var resp model.FollowResponse
	err = r.Resolver.callFollowService(http.MethodPost, "/follow", payload, &resp)
	if err != nil {
		msg := err.Error()
		return &model.FollowResponse{Message: &msg}, nil
	}

	return &resp, nil
}

// Unfollow is the resolver for the unfollow field.
func (r *mutationResolver) Unfollow(ctx context.Context, followerID string, followeeID string) (*model.FollowResponse, error) {
	// Convert IDs to int
	followerIDInt, err := strconv.Atoi(followerID)
	if err != nil {
		msg := "invalid follower ID"
		return &model.FollowResponse{Message: &msg}, nil
	}

	followeeIDInt, err := strconv.Atoi(followeeID)
	if err != nil {
		msg := "invalid followee ID"
		return &model.FollowResponse{Message: &msg}, nil
	}

	payload := map[string]int{
		"follower_id": followerIDInt,
		"followee_id": followeeIDInt,
	}

	var resp model.FollowResponse
	err = r.Resolver.callFollowService(http.MethodPost, "/unfollow", payload, &resp)
	if err != nil {
		msg := err.Error()
		return &model.FollowResponse{Message: &msg}, nil
	}

	return &resp, nil
}

// Followers is the resolver for the followers field.
func (r *queryResolver) Followers(ctx context.Context, userID string) ([]*model.User, error) {
	var resp struct {
		Followers []*model.User `json:"followers"`
	}

	endpoint := fmt.Sprintf("/users/%s/followers", userID)
	err := r.Resolver.callFollowService(http.MethodGet, endpoint, nil, &resp)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch followers: %v", err)
	}

	return convertUsers(resp.Followers), nil
}

// Following is the resolver for the following field.
func (r *queryResolver) Following(ctx context.Context, userID string) ([]*model.User, error) {
	var resp struct {
		Following []*model.User `json:"following"` // Match the Follow Service's response field
	}

	// Call Follow Service's /following endpoint
	endpoint := fmt.Sprintf("/users/%s/following", userID)
	err := r.Resolver.callFollowService(http.MethodGet, endpoint, nil, &resp)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch following: %v", err)
	}

	// Convert the response to match GraphQL type (id as string)
	return convertUsers(resp.Following), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
*/
