package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"net/http"

	"github.com/Infamous003/graphql-service/graph/model"
)

// Follow is the resolver for the follow field.
// --- mutation resolvers ---
func (r *mutationResolver) Follow(ctx context.Context, followerID int32, followeeID int32) (*model.FollowResponse, error) {
	payload := map[string]int32{
		"follower_id": followerID,
		"followee_id": followeeID,
	}

	var resp model.FollowResponse
	err := r.Resolver.callFollowService(http.MethodPost, "/follow", payload, &resp)
	if err != nil {
		msg := err.Error()
		return &model.FollowResponse{Message: &msg}, nil
	}

	return &resp, nil
}

// Unfollow is the resolver for the unfollow field.
func (r *mutationResolver) Unfollow(ctx context.Context, followerID int32, followeeID int32) (*model.FollowResponse, error) {
	payload := map[string]int32{
		"follower_id": followerID,
		"followee_id": followeeID,
	}

	var resp model.FollowResponse
	err := r.Resolver.callFollowService(http.MethodPost, "/unfollow", payload, &resp)
	if err != nil {
		msg := err.Error()
		return &model.FollowResponse{Message: &msg}, nil
	}

	return &resp, nil
}

// --- query resolvers ---
func (r *queryResolver) Followers(ctx context.Context, userID int32) ([]*model.User, error) {
	var resp struct {
		Followers []*model.User `json:"followers"`
	}

	endpoint := fmt.Sprintf("/users/%d/followers", userID)
	err := r.Resolver.callFollowService(http.MethodGet, endpoint, nil, &resp)
	if err != nil {
		return nil, fmt.Errorf("%v", err)
	}

	return convertUsers(resp.Followers), nil
}

// Following is the resolver for the following field.
func (r *queryResolver) Following(ctx context.Context, userID int32) ([]*model.User, error) {
	var resp struct {
		Following []*model.User `json:"following"`
	}

	endpoint := fmt.Sprintf("/users/%d/following", userID)
	err := r.Resolver.callFollowService(http.MethodGet, endpoint, nil, &resp)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch following: %v", err)
	}

	return convertUsers(resp.Following), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
