package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"net/http"

	"github.com/Infamous003/graphql-service/graph/model"
)

// Follow is the resolver for the follow field.
func (r *mutationResolver) Follow(ctx context.Context, followerID string, followeeID string) (*model.FollowResponse, error) {
	panic(fmt.Errorf("not implemented: Follow - follow"))
}

// Unfollow is the resolver for the unfollow field.
func (r *mutationResolver) Unfollow(ctx context.Context, followerID string, followeeID string) (*model.FollowResponse, error) {
	panic(fmt.Errorf("not implemented: Unfollow - unfollow"))
}

// Followers is the resolver for the followers field.
func (r *queryResolver) Followers(ctx context.Context, userID string) ([]*model.User, error) {
	var resp struct {
		Followers []*model.User `json:"followers"`
	}

	endpoint := fmt.Sprintf("/users/%s/followers", userID)
	err := r.Resolver.callFollowService(http.MethodGet, endpoint, nil, &resp)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch followers: %v", err)
	}

	return resp.Followers, nil
}

// Following is the resolver for the following field.
func (r *queryResolver) Following(ctx context.Context, userID string) ([]*model.User, error) {
	var resp struct {
		Following []*model.User `json:"following"`
	}

	endpoint := fmt.Sprintf("/users/%s/following", userID)
	err := r.Resolver.callFollowService(http.MethodGet, endpoint, nil, &resp)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch following: %v", err)
	}

	return resp.Following, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
*/
