// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FollowResponse struct {
	Success bool    `json:"success"`
	Message *string `json:"message,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	CreatedAt string `json:"createdAt"`
}
